<?xml version="1.0"?>
<robot name="i3e-d3_head" xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:macro name="i3e-d3_head">

    <xacro:macro name="TransmissionServo" params="joint n">
        <transmission name="tran_${n}">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${joint}">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="servo_${n}">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        </transmission>
    </xacro:macro>

    <link name="motor_neck_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/servo.stl"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.04 0.02 0.04"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.001"/>
                <inertia 
                    ixx="1e-6" ixy="0.0" ixz="0.0" 
                    iyy="1e-6" iyz="0.0" 
                    izz="1e-6"/>
        </inertial>
        
    </link>

    <joint name="motor_neck_joint" type="fixed">
        <parent link="base_link"/>
        <child link="motor_neck_link"/>
        <origin xyz="0.005 0.0 ${base_height/2}" rpy="0.0 0.0 ${PI/2}"/>
    </joint>

    <link name="neck_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/neck.stl"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/neck.stl"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.001"/>
                <inertia 
                    ixx="1e-6" ixy="0.0" ixz="0.0" 
                    iyy="1e-6" iyz="0.0" 
                    izz="1e-6"/>
        </inertial>
        
    </link>

    <joint name="neck_joint" type="revolute">
        <parent link="motor_neck_link"/>
        <child link="neck_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="-1.5707" upper="1.5707" effort="0.8" velocity="0.5"/>
        <origin xyz="0.0 0.0 0.016" rpy="0.0 0.0 0.0"/>
    </joint>

    <xacro:TransmissionServo n="neck" joint="neck_joint" />

    <link name="motor_head_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/servo.stl"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.04 0.02 0.04"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.001"/>
                <inertia 
                    ixx="1e-6" ixy="0.0" ixz="0.0" 
                    iyy="1e-6" iyz="0.0" 
                    izz="1e-6"/>
        </inertial>
    </link>

    <joint name="head_joint" type="revolute">
        <origin xyz="-0.0085 -0.117 0.142" rpy="0.0 ${-PI/2} 0.0"/>
        <parent link="neck_link"/>
        <child link="motor_head_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="-0.2618" upper="0.2618" effort="0.8" velocity="0.5"/>
    </joint>

    <xacro:TransmissionServo n="head" joint="head_joint" />

    <link name="face_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 ${-PI/2} ${PI}"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/face.stl"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 ${-PI/2} ${PI}"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/face.stl"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.001"/>
                <inertia 
                    ixx="1e-6" ixy="0.0" ixz="0.0" 
                    iyy="1e-6" iyz="0.0" 
                    izz="1e-6"/>
        </inertial>
        
    </link>

    <joint name="motor_head_joint" type="fixed">
        <origin xyz="-0.0115 -0.0435 -0.012" rpy="0.0 0.0 0.0"/>
        <child link="face_link"/>
        <parent link="motor_head_link"/>
    </joint>

    <link name="display_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/LEDs_face.stl"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/LEDs_face.stl"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.001"/>
                <inertia 
                    ixx="1e-6" ixy="0.0" ixz="0.0" 
                    iyy="1e-6" iyz="0.0" 
                    izz="1e-6"/>
        </inertial>
        
    </link>

    <joint name="display_joint" type="fixed">
        <origin xyz="-0.005 -0.02 0.0" rpy="${PI/2} ${PI/2} 0.0"/>
        <child link="display_link"/>
        <parent link="face_link"/>
    </joint>

    <link name="head_cover_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="${-PI/2} ${PI/2} ${PI/2}"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/head_cover.stl"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/head_cover.stl"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.001"/>
                <inertia 
                    ixx="1e-6" ixy="0.0" ixz="0.0" 
                    iyy="1e-6" iyz="0.0" 
                    izz="1e-6"/>
        </inertial>
        
    </link>

    <joint name="head_cover_joint" type="fixed">
        <origin xyz="0.011 0.009 0.0" rpy="0.0 ${PI} 0.0"/>
        <child link="head_cover_link"/>
        <parent link="face_link"/>
    </joint>

    
    <gazebo reference="neck_link">
        <material>Gazebo/White</material>
    </gazebo>

    <gazebo reference="face_link">
        <material>Gazebo/Whire</material>
    </gazebo>

    <gazebo reference="motor_neck_link">
        <material>Gazebo/DarkGrey</material>
    </gazebo>

    <gazebo reference="motor_head_link">
        <material>Gazebo/DarkGrey</material>
    </gazebo>

    <gazebo reference="display_link">
        <material>Gazebo/Gray</material>
    </gazebo>

    <gazebo reference="head_cover_link">
        <material>Gazebo/Blue</material>
    </gazebo>

  </xacro:macro>

</robot>
