<?xml version="1.0"?>
<robot name="i3e-d3" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <arg name="robot_namespace" default="/"/>

    <xacro:property name="PI" value="3.14159"/>
    
    <!-- Included URDF/XACRO Files -->
    <xacro:include filename="$(find i3e-d3_description)/urdf/wheel.urdf.xacro"/>
    <xacro:include filename="$(find i3e-d3_description)/urdf/accessories.urdf.xacro"/>
    <xacro:include filename="$(find i3e-d3_description)/urdf/decorations.urdf.xacro"/>
    
    <!-- Base and support sizes -->
    <xacro:property name="support_x_size" value="0.31"/>
    <xacro:property name="support_depth" value="0.009"/>
    <xacro:property name="base_x_size" value="0.35"/>
    <xacro:property name="base_y_size" value="0.22"/>
    <xacro:property name="base_z_size" value="0.085"/>
    
    <!-- Wheel Dimensions -->
    <xacro:property name="wheel_length" value="0.06"/>
    <xacro:property name="wheel_radius" value="0.065"/>
    <!-- Wheel Mounting Positions -->
    <xacro:property name="wheel_xf_offset" value="0.09068514"/>
    <xacro:property name="wheel_xr_offset" value="0.08931486"/>
    <xacro:property name="wheel_y_offset" value="${wheel_length/2 + base_y_size/2 + 0.005}"/>
    <xacro:property name="wheel_z_offset" value="-0.02805562"/>

    <!-- Base link is the center of the robot -->
    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/chassis.stl"/>
            </geometry>
            <material name="blue">
                <color rgba="0.0 0.0 1.0 1.0"/>
            </material>
        </visual>
        <collision> 
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
    </link>

    <!-- Base footprint link is on the ground under the robot-->
    <link name="base_footprint"/>
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0.0 0.0 ${wheel_z_offset - wheel_radius}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>

    <!-- Base support link -->
    <link name="support_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.4358"/>
            <inertia 
                ixx="1.7607e-3" ixy="0.0" ixz="0.0" 
                iyy="3.4930e-3" iyz="0.0" 
                izz="5.2477e-3"/>
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${support_x_size} ${base_y_size} ${support_depth}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${support_x_size} ${base_y_size} ${support_depth}"/>
            </geometry>
        </collision>
    </link>

    <joint name="support_joint" type="fixed">
        <origin xyz="-0.008 0.0 ${-base_z_size/2}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="support_link"/>
    </joint>
    
    <!-- Base inertial link -->
    <link name="inertial_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <mass value="3"/>
            <inertia
              ixx="2.15524e-2" ixy="0.0" ixz="5.5686e-4"
              iyy="3.76598e-2" iyz="0.0"
              izz="5.25852e-2"/>
        </inertial> 
    </link>

    <joint name="inertial_joint" type="fixed">
        <parent link="base_link"/>
        <child link="inertial_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <xacro:i3e-d3_decorate/>

    <!-- I3E-D3 wheel macros -->
    <xacro:i3e-d3_wheel prefix="front_left">
        <origin xyz="${wheel_xf_offset} ${wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_wheel>
    <xacro:i3e-d3_wheel prefix="front_right">
        <origin xyz="${wheel_xf_offset} ${-wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_wheel>
    <xacro:i3e-d3_wheel prefix="rear_left">
        <origin xyz="${-wheel_xr_offset} ${wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_wheel>
    <xacro:i3e-d3_wheel prefix="rear_right">
        <origin xyz="${-wheel_xr_offset} ${-wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_wheel>

    <!-- Sensors -->
    <xacro:i3e-d3_lidar>
        <origin xyz="0.0469 0.0 ${base_z_size/2 + 0.025}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_lidar>
    <xacro:i3e-d3_camera>
        <origin xyz="-0.005 0.0 ${base_z_size/2 + camera_box_size + 0.025}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_camera>

    <gazebo reference="base_link"><material>Gazebo/Yellow</material></gazebo>
    <gazebo reference="support_link"><material>Gazebo/DarkYellow</material></gazebo>

    <!-- Gazebo ROS Control Plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>$(arg robot_namespace)</robotNamespace>
            <legacyModeNS>true</legacyModeNS>
        </plugin>
    </gazebo>
    
</robot>
