<?xml version="1.0"?>
<robot name="i3e-d3" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:arg name="robot_namespace" default="i3e_d3"/>
    <xacro:arg name="use_open_manipulator" default="false"/>

    <xacro:property name="PI" value="3.14159"/>
    
    <!-- Included URDF/XACRO Files -->
    <xacro:include filename="$(find i3e-d3_description)/urdf/wheel.urdf.xacro"/>
    <xacro:include filename="$(find i3e-d3_description)/urdf/accessories.urdf.xacro"/>
    <xacro:include filename="$(find i3e-d3_description)/urdf/decorations.urdf.xacro"/>
    
    <!-- Base, head and neck sizes -->
    <xacro:property name="base_radius" value="0.155"/>
    <xacro:property name="base_height" value="0.342"/>

    <xacro:property name="head_x_size" value="0.20"/>
    <xacro:property name="head_y_size" value="0.20"/>
    <xacro:property name="head_z_size" value="0.215"/>

    <xacro:property name="neck_x_size" value="0.08"/>
    <xacro:property name="neck_y_size" value="0.08"/>
    <xacro:property name="neck_z_size" value="0.07"/>

    <!--xacro:property name="cog_x" value="-0.013"/>
    <xacro:property name="cog_z" value="-0.23825904"/-->
    <xacro:property name="cog_x" value="0"/>
    <xacro:property name="cog_z" value="${-base_height/2}"/>
    
    <xacro:property name="base_weight" value="0.515"/>
    <!-- Wheel Dimensions -->
    <xacro:property name="wheel_length" value="0.0762"/>
    <xacro:property name="wheel_radius" value="0.088"/>
    <!-- Wheel Mounting Positions -->
    <xacro:property name="wheel_x_offset" value="0"/>
    <xacro:property name="wheel_y_offset" value="${wheel_length/2 + base_radius + 0.005}"/>
    <xacro:property name="wheel_z_offset" value="${cog_z + 0.05}"/>

    <!-- Base link is the center of the robot -->
    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}"/>
            </geometry>
            <material name="blue">
                <color rgba="0.0 0.0 1.0 1.0"/>
            </material>
        </visual>
        <collision> 
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}"/>
            </geometry>
        </collision>
    </link>

    <!-- Base footprint link is on the ground under the robot-->
    <link name="base_footprint"/>
    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0.0 0.0 ${wheel_z_offset - wheel_radius}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>
    
    <!-- Base inertial link -->
    <link name="inertial_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
            <mass value="3"/>
            <inertia
              ixx="2.15524e-2" ixy="0.0" ixz="5.5686e-4"
              iyy="3.76598e-2" iyz="0.0"
              izz="5.25852e-2"/>
        </inertial> 
    </link>

    <joint name="inertial_joint" type="fixed">
        <parent link="base_link"/>
        <child link="inertial_link"/>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="neck">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${neck_x_size} ${neck_y_size} ${neck_z_size}"/>
            </geometry>
            <material name="blue">
                <color rgba="0.0 0.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${neck_x_size} ${neck_y_size} ${neck_z_size}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6"/>
        </inertial>
    </link>

    <joint name="neck_joint" type="fixed">
        <parent link="base_link"/>
        <child link="neck"/>
        <origin xyz="-0.077 0.0 ${neck_z_size/2 + 0.262}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="head">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <mesh filename="package://i3e-d3_description/meshes/head.stl"/>
            </geometry>
            <material name="blue">
                <color rgba="0.0 0.0 1.0 1.0"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${head_x_size} ${head_y_size} ${head_z_size}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6"/>
        </inertial>
    </link>

    <joint name="head_joint" type="fixed">
        <parent link="base_link"/>
        <child link="head"/>
        <origin xyz="-0.077 0.0 ${neck_z_size + 0.262 + 0.096}" rpy="0.0 0.0 0.0"/>
    </joint>


    <xacro:i3e-d3_decorate/>

    <!-- I3E-D3 wheel macros -->
    <xacro:i3e-d3_wheel prefix="left">
        <origin xyz="${wheel_x_offset} ${wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_wheel>
    <xacro:i3e-d3_wheel prefix="right">
        <origin xyz="${wheel_x_offset} ${-wheel_y_offset} ${wheel_z_offset}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_wheel>

    <xacro:i3e-d3_caster prefix="front">
        <origin xyz="0.11 0.0 ${wheel_z_offset - wheel_radius + 0.0351}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_caster>
    <xacro:i3e-d3_caster prefix="back">
        <origin xyz="-0.11 0.0 ${wheel_z_offset - wheel_radius + 0.0351}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_caster>

    
    <!-- Sensors -->
    <xacro:i3e-d3_lidar>
        <origin xyz="${base_radius/2} 0.0 ${base_height + cog_z + 0.025}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_lidar>
    <xacro:i3e-d3_camera>
        <origin xyz="0.03 0.0 ${base_height + cog_z + neck_z_size + 0.04}" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_camera>
    <xacro:i3e-d3_imu>
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:i3e-d3_imu>

    <gazebo reference="base_link"><material>Gazebo/Yellow</material></gazebo>
    <gazebo reference="neck"><material>Gazebo/DarkGrey</material></gazebo>
    <gazebo reference="head"><material>Gazebo/Yellow</material></gazebo>

    <gazebo reference="caster">
        <material>Gazebo/DarkGrey</material>
        <mu1 value="0.0"/>
        <mu2 value="0.0"/>
    </gazebo>

    <!-- Gazebo ROS Control Plugin -->
    <!--gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>$(arg robot_namespace)</robotNamespace>
            <legacyModeNS>true</legacyModeNS>
        </plugin>
    </gazebo-->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
      <controlPeriod>0.001</controlPeriod>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>    
  
</robot>
