<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="i3e-d3_wheel">
    <xacro:property name="husky_wheel_length" value="0.1143" />
    <xacro:property name="husky_wheel_radius" value="0.1651" />

    <xacro:macro name="i3e-d3_wheel" params="prefix *joint_pose">
        <link name="${prefix}_wheel_link">
            <inertial>
                <!-- Need to adjust inertia matrix -->
                <origin xyz="0.0 0.0 0.0"/>
                <mass value="1.1"/>
                <inertia
                  ixx="2.70474e-4" ixy="0.0" ixz="0.0"
                  iyy="4.38099e-4" iyz="0.0"
                  izz="2.70474e-4"/>
            </inertial>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://i3e-d3_description/meshes/wheel_husky.dae"
                          scale="${wheel_radius/husky_wheel_radius} ${wheel_length/husky_wheel_length} ${wheel_radius/husky_wheel_radius}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>
        </link>

        <!-- Need to adjust gazebo properties -->
        <gazebo reference="${prefix}_wheel_link">
            <material>Gazebo/DarkGrey</material>
            <mu1 value="1.0"/>
            <mu2 value="1.0"/>
            <kp value="10000000.0" />
            <kd value="1" />
            <fdir1 value="1 0 0"/>
        </gazebo>

        <joint name="${prefix}_wheel" type="continuous">
            <xacro:insert_block name="joint_pose"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0" rpy="0.0 0.0 0.0"/>
        </joint>

        <transmission name="${prefix}_wheel_trans" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${prefix}_wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${prefix}_wheel">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>

    </xacro:macro>


    <!--xacro:macro name="i3e-d3_caster" params="prefix *joint_pose"-->
    <xacro:macro name="i3e-d3_caster" params="prefix">

        <link name="${prefix}_caster_wheel">
            <visual>
                <geometry>
                    <sphere radius="0.01"/>
                </geometry>
                <material name="black">
                    <color rgba="0.0 0.0 0.0 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="0.01"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                <mass value="0.01"/>
                <inertia ixx="4e-7" ixy="0.0" ixz="0.0" iyy="4e-7" iyz="0.0" izz="4e-7"/>
            </inertial>
        </link>

        <link name="${prefix}_caster_support">
            <visual>
                <geometry>
                    <cylinder radius="0.011" length="0.025"/>
                </geometry>
                <material name="gray">
                    <color rgba="0.7 0.7 0.7 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.011" length="0.025"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                <mass value="0.01"/>
                <inertia ixx="8.2333e-7" ixy="0.0" ixz="0.0" iyy="8.2333e-7" iyz="0.0" izz="6.05e-7"/>
            </inertial>
        </link>

        <link name="${prefix}_caster_right">
            <visual>
                <geometry>
                    <box size="0.026 0.003 0.01"/>
                </geometry>
                <material name="gray">
                    <color rgba="0.7 0.7 0.7 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="0.026 0.003 0.01"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                <mass value="0.01"/>
                <inertia ixx="9.0833e-8" ixy="0.0" ixz="0.0" iyy="6.4667e-7" iyz="0.0" izz="5.7083e-7"/>
            </inertial>
        </link>

        <link name="${prefix}_caster_left">
            <visual>
                <geometry>
                    <box size="0.026 0.003 0.01"/>
                </geometry>
                <material name="gray">
                    <color rgba="0.7 0.7 0.7 1"/>
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="0.026 0.003 0.01"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                <mass value="0.01"/>
                <inertia ixx="9.0833e-8" ixy="0.0" ixz="0.0" iyy="6.4667e-7" iyz="0.0" izz="5.7083e-7"/>
            </inertial>
        </link>

        <joint name="${prefix}_caster_support_joint" type="continuous">
            <origin xyz="-0.049 0.0 -0.0125" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="${prefix}_caster_support"/>
            <axis xyz="0 0 1"/>
        </joint>

        <joint name="${prefix}_caster_right_joint" type="fixed">
            <origin xyz="-0.013 0.0115 -0.0125" rpy="0 0 0"/>
            <parent link="${prefix}_caster_support"/>
            <child link="${prefix}_caster_right"/>
            <axis xyz="0 0 1"/>
        </joint>

        <joint name="${prefix}_caster_left_joint" type="fixed">
            <origin xyz="-0.013 -0.0115 -0.0125" rpy="0 0 0"/>
            <parent link="${prefix}_caster_support"/>
            <child link="${prefix}_caster_left"/>
            <axis xyz="0 0 1"/>
        </joint>

        <joint name="${prefix}_caster_wheel_right_joint" type="continuous">
            <origin xyz="-0.013 -0.0115 0.0" rpy="1.5707 0 0"/>
            <parent link="${prefix}_caster_right"/>
            <child link="${prefix}_caster_wheel"/>
            <axis xyz="0 0 1"/>
        </joint>
        
        <joint name="${prefix}_caster_wheel_left_joint" type="continuous">
            <origin xyz="-0.013 0.0115 0.0" rpy="1.5707 0 0"/>
            <parent link="${prefix}_caster_left"/>
            <child link="${prefix}_caster_wheel"/>
            <axis xyz="0 0 1"/>
            <mimic joint="${prefix}_caster_wheel_right_joint"/>
        </joint>        

    </xacro:macro>

</robot>
