<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="i3e-d3_wheel">
    <xacro:property name="husky_wheel_length" value="0.1143" />
    <xacro:property name="husky_wheel_radius" value="0.1651" />

    <xacro:macro name="i3e-d3_wheel" params="prefix *joint_pose">
        <link name="${prefix}_wheel_link">
            <inertial>
                <!-- Need to adjust inertia matrix -->
                <origin xyz="0.0 0.0 0.0"/>
                <mass value="1.1"/>
                <inertia
                  ixx="2.70474e-4" ixy="0.0" ixz="0.0"
                  iyy="4.38099e-4" iyz="0.0"
                  izz="2.70474e-4"/>
            </inertial>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://i3e-d3_description/meshes/wheel_husky.dae"
                          scale="${wheel_radius/husky_wheel_radius} ${wheel_length/husky_wheel_length} ${wheel_radius/husky_wheel_radius}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>
        </link>

        <!-- Need to adjust gazebo properties -->
        <gazebo reference="${prefix}_wheel_link">
            <mu1 value="1.0"/>
            <mu2 value="1.0"/>
            <kp value="10000000.0" />
            <kd value="1" />
            <fdir1 value="1 0 0"/>
        </gazebo>

        <joint name="${prefix}_wheel" type="continuous">
            <xacro:insert_block name="joint_pose"/>
            <parent link="base_link"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="0 1 0" rpy="0.0 0.0 0.0"/>
        </joint>

        <transmission name="${prefix}_wheel_trans" type="SimpleTransmission">
            <type>transmission_interface/SimpleTransmission</type>
            <actuator name="${prefix}_wheel_motor">
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
            <joint name="${prefix}_wheel">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
        </transmission>

    </xacro:macro>


    <xacro:macro name="i3e-d3_caster" params="prefix *joint_pose">
        
        <link name="${prefix}_caster_base">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.005"/>
                <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6"/>
            </inertial>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="0.05 0.05 0.005"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="0.05 0.05 0.005"/>
                </geometry>
            </collision>
        </link>

        <link name="${prefix}_caster_wheel_support">
            
            <xacro:property name="caster_wheel_support_box">
                <geometry>
                    <box size="0.025 0.0045 0.02"/>
                </geometry>
            </xacro:property>
            
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.02"/>
                <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6"/>
            </inertial>
            <visual>
                <origin xyz="0.0 0.016 0.0" rpy="0.0 0.0 0.0"/>
                <xacro:insert_block name="caster_wheel_support_box"/>
            </visual>
            <visual>
                <origin xyz="0.0 -0.016 0.0" rpy="0.0 0.0 0.0"/>
                <xacro:insert_block name="caster_wheel_support_box"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.016 0.0" rpy="0.0 0.0 0.0"/>
                <xacro:insert_block name="caster_wheel_support_box"/>
            </collision>
            <collision>
                <origin xyz="0.0 -0.016 0.0" rpy="0.0 0.0 0.0"/>
                <xacro:insert_block name="caster_wheel_support_box"/>
            </collision>
        </link>

        <link name="${prefix}_caster_wheel">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.01"/>
                <inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6"/>
            </inertial>
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <sphere radius="0.014"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <sphere radius="0.014"/>
                </geometry>
            </collision>
        </link>

        <joint name="${prefix}_caster_base_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_caster_base"/>
            <xacro:insert_block name="joint_pose"/>
        </joint>

        <joint name="${prefix}_caster_wheel_support_joint" type="continuous">
            <parent link="${prefix}_caster_base"/>
            <child link="${prefix}_caster_wheel_support"/>
            <axis xyz="0 0 1"/>
            <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
        </joint>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="${prefix}_caster_wheel_support"/>
            <child link="${prefix}_caster_wheel"/>
            <axis xyz="0 1 0"/>
            <origin xyz="0 0 -0.011" rpy="0 0 0"/>
        </joint>
        
    </xacro:macro>

</robot>
