obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.26, 0.3], [-0.26, -0.3], [0.18, -0.3], [0.18, 0.3]]

inflation_radius: 0.55

observation_sources: laser_scan_sensor 

laser_scan_sensor: {sensor_frame: 3irobotix_lidar, data_type: LaserScan, topic: i3e_d3/laser/scan, marking: true, clearing: true}
