# Teleop configuration for PS4 joystick using the x-pad configuration.
# Left thumb-stick up/down for velocity, left/right for twist
# Left shoulder button for enable
# Right shoulder button for enable-turbo
#
#          L1                                       R1
#          L2                                       R2
#       _=====_                                  _=====_
#      / _____ \                                / _____ \
#    +.-'_____'-.------------------------------.-'_____'-.+
#   /   |     |  '.        S O N Y           .'  |  _  |   \
#  / ___| /|\ |___ \                        / ___| /_\ |___ \      (Y)
# / |      |      | ;                      ; | _         _ ||
# | | <---   ---> | |                      | ||_|       (_)||  (X)     (B)
# | |___   |   ___| ;                      ; |___       ___||
# |\    | \|/ |    /  _      ____      _   \    | (X) |    /|      (A)
# | \   |_____|  .','" "',  (_PS_)  ,'" "', '.  |_____|  .' |
# |  '-.______.-' /       \        /       \  '-._____.-'   |
# |               |  LJ   |--------|  RJ   |                |
# |              /\       /        \       /\               |
# |             /  '.___.'          '.___.'  \              |
# |            /                              \             |
#  \          /                                \           /
#   \________/                                  \_________/
#
#          ^ x
#          |
#          |
#  y <-----+      Accelerometer axes
#           \
#            \
#             > z (out)
#
# BUTTON         Value
#   1              0
#   2              1
#   3              2
#   4              3
#   L1             4
#   R1             5
#   L2             6
#   R2             7
#   SELECT         8
#   START          9
#   L3             10
#   R3             11
#
#    AXIS        Value
# Left Horiz.      0
# Left Vert.       1
# Right Horiz.     2
# Right Vert.      3
# Button Horiz.    4
# Button Vert.     5
#

teleop_twist_joy:
  axis_linear: 5
  scale_linear: 1.0
  scale_linear_turbo: 2.0
  axis_angular: 4
  scale_angular: 1.4
  enable_button: 2
  enable_turbo_button: 3
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
  dev: /dev/input/js0
